aliases:
  literary_fiction:
    - literary
    - literary fiction
    - lit fic
    - literary fic
  commercial_fiction:
    - commercial
    - commercial fiction
    - commercial fic
  science_fiction:
    - sci-fi
    - scifi
    - sf
    - science fiction
    - sci fi
  fantasy:
    - epic fantasy
    - urban fantasy
    - dark fantasy
    - cozy fantasy
    - contemporary fantasy
    - high fantasy
    - low fantasy
  romance:
    - rom-com
    - romcom
    - romantic comedy
    - contemporary romance
    - spicy romance
    - dark romance
    - romantic suspense
    - why-choose
    - why choose
    - romantasy
  mystery:
    - cozy mystery
    - cozy mysteries
    - cozies
    - mysteries
    - locked room mystery
  thriller:
    - thrillers
    - psychological thriller
    - domestic thriller
  horror:
    - dark horror
  historical_fiction:
    - historical
    - historical fiction
    - hist fic
    - historical fic
  young_adult:
    - ya
    - YA
    - young adult
  middle_grade:
    - mg
    - MG
    - middle-grade
  picture_books:
    - picture book
    - pb
    - PB
  memoir:
    - memoirs
    - personal memoir
  narrative_nonfiction:
    - narrative non-fiction
    - creative nonfiction
    - creative non-fiction
    - narrative nf
  self_help:
    - self-help
    - personal development
  biography:
    - biographies
    - bio
  womens_fiction:
    - women's fiction
    - women's fic
    - womens fic
    - chick-lit
    - chick lit
    - book club fiction
  upmarket_fiction:
    - upmarket
    - upmarket fic
  speculative_fiction:
    - speculative
    - spec fic
  contemporary_fiction:
    - contemporary
    - contemporary fic
  crime_fiction:
    - crime
    - crime fic
  suspense:
    - domestic suspense
  true_crime:
    - true-crime
  graphic_novels:
    - graphic novel
    - comics
    - graphic novels & comics
  health_wellness:
    - health & wellness
    - health and wellness
    - wellness
  paranormal:
    - paranormal romance
    - paranormal fiction
  dystopian:
    - dystopia
    - post-apocalyptic
  adventure:
    - adventure fiction
  humor:
    - comedy
    - humorous fiction
  essay_collection:
    - essays
    - personal essays
