"""Shared FastAPI dependencies: auth, session, rate limiting, embedding model."""
from __future__ import annotations

import logging
import time
import uuid

from fastapi import Cookie, Depends, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy.orm import Session

from autoquery.api.auth import decode_token
from autoquery.database.db import get_db
from autoquery.database.models import User
from autoquery.embeddings.model import OllamaEmbeddingModel

logger = logging.getLogger(__name__)

_bearer_scheme = HTTPBearer(auto_error=True)
_bearer_scheme_optional = HTTPBearer(auto_error=False)

# Singleton embedding model
_embedding_model: OllamaEmbeddingModel | None = None


def get_embedding_model() -> OllamaEmbeddingModel:
    global _embedding_model
    if _embedding_model is None:
        _embedding_model = OllamaEmbeddingModel()
    return _embedding_model


def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(_bearer_scheme),
    db: Session = Depends(get_db),
) -> User:
    """Decode JWT and return the User. Raises 401 on failure."""
    payload = decode_token(credentials.credentials)
    if payload.get("type") != "access":
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token type")
    user_id = payload.get("sub")
    if user_id is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")
    user = db.query(User).filter(User.id == int(user_id)).first()
    if user is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found")
    return user


def get_optional_user(
    request: Request,
    db: Session = Depends(get_db),
) -> User | None:
    """Return the User if a valid Bearer token is present, else None."""
    auth = request.headers.get("Authorization", "")
    if not auth.startswith("Bearer "):
        return None
    token = auth[len("Bearer "):]
    try:
        payload = decode_token(token)
    except HTTPException:
        return None
    if payload.get("type") != "access":
        return None
    user_id = payload.get("sub")
    if user_id is None:
        return None
    return db.query(User).filter(User.id == int(user_id)).first()


def get_session_id(
    request: Request,
    session_id: str | None = Cookie(default=None),
) -> str:
    """Read session_id cookie or use the one generated by middleware."""
    if session_id:
        return session_id
    # Use the session ID generated by the middleware
    return getattr(request.state, "generated_session_id", None) or str(uuid.uuid4())


class RateLimiter:
    """Sliding-window rate limiter using Redis. Falls back to no-op if Redis unavailable."""

    def __init__(self, max_calls: int, period_seconds: int, key_prefix: str):
        self.max_calls = max_calls
        self.period_seconds = period_seconds
        self.key_prefix = key_prefix

    async def __call__(self, request: Request) -> None:
        redis = getattr(request.app.state, "redis", None)
        if redis is None:
            return  # No-op in dev/test

        # Key by IP or user
        client_ip = request.client.host if request.client else "unknown"
        key = f"ratelimit:{self.key_prefix}:{client_ip}"
        now = time.time()
        window_start = now - self.period_seconds

        try:
            pipe = redis.pipeline()
            pipe.zremrangebyscore(key, 0, window_start)
            pipe.zadd(key, {str(now): now})
            pipe.zcard(key)
            pipe.expire(key, self.period_seconds)
            results = await pipe.execute()
            count = results[2]
        except Exception:
            logger.warning("Rate limiter Redis error, allowing request")
            return

        if count > self.max_calls:
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail="Rate limit exceeded",
            )
